FROM python:3.10-slim

# Set working directory inside container
WORKDIR /app

# Copy application code
COPY main.py .

# Install dependencies
RUN pip install fastapi uvicorn

# Run FastAPI app
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"]
